### ISSUE TITLE
Intermediate namespace scope between macro_insert and entities

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#1]
As it is now, the entity's namespace scope is directly pointed to that that of the calling macro_insert & co. This creates a lot of duplication that opens the door to bugs.

Suppose the following setup:

* a **macro_insert** with following keyvalues
* - brushtemplate = 1
* a **func_door** with following keyvalues
* - targetname = `{'brushmodel' if brushtemplate else ('brush' + iid())}` (Expr. 1)
* - target = `{'walltogglemodel' if brushtemplate else ('walltoggle' + iid())}` (Expr. 2)
* a **light_shadow** that targets the func_door. it has to duplicate the exact same expression:
* - target = `{'brushmodel' if brushtemplate else ('brush' + iid())}`  (Expr. 1 repeated)
* a **func_wall_toggle**
* - targetname = `{'walltogglemodel' if brushtemplate else ('walltoggle' + iid())}` (Expr. 2 repeated)
* repeat with as many entities that may need to target each other

The proposal is to add another namespace scope that precalculates all the unique values that entites in the template might need. Suppose we add this support to macro_template itself, or a new macro_keyvalues inside the template with the following keyvalues:

* **macro_template** or **macro_keyvalues**
* - doorname = `{'brushmodel' if brushtemplate else ('brush' + iid())}`
* - walltogglename = `{'walltogglemodel' if brushtemplate else ('walltoggle' + iid())}`

These will be evaluated first before any entity in the template. The entities in turn can reference these keyvalues:

* **func_door**
* - targetname = {doorname}
* - target = {walltogglename}
* **func_wall_toggle**
* - targetname = {walltogglename}
* **light_shadow**
* - target = {doorname}

Now the expressions in the entities are much cleaner and less prone to bugs, because we calculate the values once per instance.

**Comment by mfaizsyahmi** [comment]
Or... just make macro_inserts inside macro_templates. But some people might want to MESS in several ways. Worth considering still.

**Comment by pwitvoet** [comment]
Evaluating custom macro_template attributes and using them as locals was actually on my todo list. It would definitely make things more convenient. I'll include this for the next release.

**Comment by mfaizsyahmi** [comment]
> 
> 
> Evaluating custom macro_template attributes and using them as locals was actually on my todo list. It would definitely make things more convenient. I'll include this for the next release.

nice!

**Comment by pwitvoet** [comment]
This has been implemented now and will be available in MESS 1.2.
