### ISSUE TITLE
Clarify how to get `_mess_merge_entity_master` to work

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#12]
I've used two macro_brushes that should combine into one entity using `_mess_merge_entity_id`. For one of them I passed a `merge_entity_master = 1` to mark it as master. then on the brush entities in the template I have `_mess_merge_entity_master = {merge_entity_master}` but apparently this doesn't make this work. I had to redo the parent template so that the one not being master is a later entity in the .map's entity list.

It seems to me that the existence of the keyvalue makes it a master even if the value is `none`. So I had it rewritten to `{merge_entity_master ? '_mess_merge_entity_master' : ''} = 1` though I dunno if it is the intended way since I've solved my problem another way.

The docs don't have an example on how to do this. A clarification is appreciated.

**Comment by pwitvoet** [comment]
It's indeed the presence of the `_mess_merge_entity_master` key that matters. Now that you mention it, I think it makes more sense to make it a 'boolean' property like `_mess_remove_if`. That would make it more consistent and easier to use.

I agree that the documentation for special properties could use some examples.

**Comment by pwitvoet** [comment]
Behavior has been improved in a64b32649b08a1c89db7e5936558e03e2424a7eb and documentation has been updated in 77ca414863d7339542829cd36fb5e4750284c878 (this documents the current behavior - when 1.2.3 is released I'll update it to reflect the new boolean behavior).
