### ISSUE TITLE
[feature] bitwise operators

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#13]
Say I want to use one keyvalue to store information in a bitwise fashion, just like `effects` (entity effects). Currently bitwise operators are not implemented in mess except for spawnflags, and you're left with only modulo (%) for reading bits.

Implementing the standard bitwise operators into mess would be of much benefit imo. I don't mind it to be a much later feature on the timeline since I don't plan on using it much to write bitflags, just read (which % can do). But that could change if more people uses mess, who knows.

**Comment by pwitvoet** [comment]
Bitwise operators weren't a priority for me, and it's a bit tricky to figure out how they should behave given that MScript only has one numeric type, a 64-bit floating point (I should add that fact to the documentation).

Maybe it's sensible for bitwise operators to first round their operands the nearest integer values and then perform the bitwise operation?

**Comment by pwitvoet** [comment]
I've added `<<`, `>>`, `&`, `^`, `|` and `~` operators to MScript. They behave as their counterparts in Javascript: numbers are truncated and converted to signed 32-bit integers before the bitwise operation is performed. This will be available in v1.2.3.
