### ISSUE TITLE
[feature] produce a signal file when processing a map file succeeds

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#15]
Built-in compile runners in editors like Hammer and JACK can be made to check that a file with a particular extension is produced after a compile tool is run. This is to check whether the compile step succeeds or not, and whether to proceed with the rest of the compilation. Most of the time it's a requisite file for the next compile tool (e.g. portal file for VIS) and proceeding without the file will just make the next compile tool fail, so this feature stops the failure early.

I propose MESS produce a dummy file for this purpose. The presence of the file signals to the compiler that the compile succeeded and compilation can proceed, because as of this moment the compile continues even when mess expansion fails, and this can cause cascading failure that may produce a finished BSP but actually crashes the game when run. ATM MESS may exit with code > 0 but Hammer/JACK compile runner doesn't appear to check these.

**Comment by pwitvoet** [comment]
You can already do this if you pass a different output path to MESS.

For example, you could first rename the exported .map file:
`Rename file: $path/$file.$ext $path/$file.original.$ext`

And then call MESS as following:
`MESS.exe "$path/$file.original.$ext" "$path/$file.$ext"`

You can then use the existence of `$path/$file.$ext` to determine whether MESS succeeded.

**Comment by mfaizsyahmi** [comment]
That's an added step.

In the meantime, I found a different solution: An entity in the void with `_mess_remove_if`. If MESS runs successfully it will be removed; if it fails it will remain and BSP will fail with a leak.

**Comment by pwitvoet** [comment]
True, it's an extra step, but it's not difficult to set up, and after that it's fully automatic. Maybe I should add a note about this to the setup guide.

The entity trick is clever, but I don't think it can be automated. I was thinking of using a rewrite rule to add a `_mess_attached_template_map` property to the `worldspawn` entity, to pull in a template map that contains such an entity - but that would require MESS to run successfully, defeating the point.
