### ISSUE TITLE
Typo in documentation for `array.all()`

### ISSUE THREAD

**Issue by dwz95** [pwitvoet/mess#17]
The example for `array.all()` seems to refer to `array.any()` instead.

https://github.com/pwitvoet/mess/blob/d992529b6a5c67eccbc5278b6fc3df9b0fee1e06/docs/data-types.html#L589

**Comment by pwitvoet** [comment]
Thanks for pointing that out! I just went over the code examples and found several similar errors. They should be fixed now.
