### ISSUE TITLE
Parent `macro_insert`'s angles getting messed up

### ISSUE THREAD

**Issue by dwz95** [pwitvoet/mess#18]
An entity (`particle_shooter` from Featureful SDK, in case it's somehow relevant) within a `macro_template` sets its `angles` to `{angles}`. That, supposedly, reads the `angles` property of the `macro_insert` instantiating it. It, in turn, has its `angles` set to `17 270 0`.

Expected behavior is that the `angles` of the `particle_shooter` will get set to `17 270 0`. Instead, the angles end up being set to `16.236122131347656 174.89207458496094 -17.729080200195312`.

Example map for reproduction is provided:
[mess_bad_angles.zip](https://github.com/user-attachments/files/18022324/mess_bad_angles.zip)

The `.rmf` file is the source map, the `.map` file is the result of macro expansion.

MESS version used is `1.2.3.0`.

**Comment by pwitvoet** [comment]
When an instance is created, the content of the chosen template is automatically moved, rotated and scaled depending on the position, orientation and scale of the instance-creating macro entity. That affects not only brushes but also the `origin`, `angles` and `scale` properties of entities.

So by setting the `angles` of the `particle_shooter` to `{angles}`, you're effectively rotating it twice - first `{angles}` is evaluated to `17 270 0`, and then the entity is rotated by `17 270 0`, which produces the angles that you're seeing. Set `angles` to `0 0 0` instead.
