### ISSUE TITLE
`@mess;` without preceding `@mess rewrite` breaks rewrites

### ISSUE THREAD

**Issue by mfaizsyahmi** [pwitvoet/mess#9]
I find the recurring need to disable/enable certain rewrite rules. I figure just invalidating the starting block e.g. `@///mess ...` would work but the dangling ending block `@mess;` ended up bypassing all subsequent blocks. So I had to invalidate the ending blocks as well e.g. `@///mess;`

I thought the parser would not match a block until it finds a starting block but apparently the parsing works some other way.

I'm writing this issue to take note of this behaviour. Preferably the parser should ignore dangling ending blocks, or in other words only start recognizing it after a starting block. Otherwise issue a warning a console.

**Comment by pwitvoet** [comment]
I think it makes sense to ignore disconnected `@MESS;` tokens, yes.

**Comment by pwitvoet** [comment]
Fixed in 2bf6d4e0961cd42554791e091446b3bd1c7a81c2
